# Generated by Django 4.2.8 on 2024-10-11 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookformat',
            unique_together={('book_author_name', 'format')},
        ),
    ]
