# Generated by Django 4.2.8 on 2024-10-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_', '0002_alter_bookformat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookformat',
            name='image_1',
            field=models.URLField(default='https://res.cloudinary.com/dh8vfw5u0/image/upload/v1702231959/rmpi4l8wsz4pdc6azeyr.ico', null=True),
        ),
        migrations.AlterField(
            model_name='bookformat',
            name='image_2',
            field=models.URLField(default='https://res.cloudinary.com/dh8vfw5u0/image/upload/v1702231959/rmpi4l8wsz4pdc6azeyr.ico', null=True),
        ),
        migrations.AlterField(
            model_name='bookformat',
            name='image_3',
            field=models.URLField(default='https://res.cloudinary.com/dh8vfw5u0/image/upload/v1702231959/rmpi4l8wsz4pdc6azeyr.ico', null=True),
        ),
    ]
