# Generated by Django 4.2.8 on 2024-08-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_alter_administratorprofile_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
